--app_data
CREATE USER app_data IDENTIFIED BY "b6uUG1J4ExNepoQ"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_code
CREATE USER app_code IDENTIFIED BY "PcW0bO8UuvtBzfs"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_admin
CREATE USER app_admin IDENTIFIED BY "tmaLTXw9EivgRCr"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_user
CREATE USER app_user IDENTIFIED BY "TOtwoJu0eeRmg6I"
ENABLE EDITIONS;
